Hotfix/not existing user
TheDevengers/welldone-FE pull request #29
Opened 2019-10-20 20:48 UTC by basanta79

### Summary
Fix a problem in login with wrong user or password

2019-10-20 20:49 UTC, Ferveloper approved these changes

2019-10-20 21:07 UTC, SabrinaFZ requested changes

2019-10-20 21:07 UTC, SabrinaFZ commented on src/utils/api.js
> +        if (res.status!==200){
Mejor comprobar `if(res && res.status !==200)` ya que si es `undefined` puede dar problemas

2019-10-20 22:45 UTC, basanta79 commented on src/utils/api.js
> +        if (res.status!==200){
ok cambiado

2019-10-20 23:04 UTC, bri06 approved these changes

2019-10-21 00:01 UTC, hvctgr approved these changes

2019-10-21 07:57 UTC, SabrinaFZ approved these changes

2019-10-21 20:23 UTC, merged