Feature/user signup
TheDevengers/welldone-FE pull request #6
Opened 2019-09-23 21:25 UTC by hvctgr

Añadido logo abreviado y logo grande (el txt son los pasos para hacer uno)

Componente Datepicker añadido para su posterior uso

Funcionalidad de signup realizada

2019-09-23 21:38 UTC, SabrinaFZ commented on src/components/Signup/Signup.js
> +      if (result.error === false) {
Aquí lo cambiaría a `if(result && !result.error)` 

- Primero compruebas que result no es undefined ya que si es undefined podría dar una excepción cuando intenta a acceder a una propiedad que no viene definida dentro de result

2019-09-23 21:43 UTC, SabrinaFZ commented on src/components/commons/Logo/crear_logo_pasos.txt
> +Seleccionar el logo de acuerdo al texto introducido y bajar al pc como SVG:
Podrías cambiar el nombre del archivo a inglés? Para mantener así el mismo idioma de todos los ficheros en todo el directorio? Gracias!

2019-09-23 21:46 UTC, SabrinaFZ commented on src/utils/apiSignup.js
> +const BASE_URL = 'http://127.0.0.1:8000/api/v1/';
Mejor saca esto al archivo .env, por si en algún momento hay que acceder a esta URL desde otro lado

2019-09-23 21:46 UTC, SabrinaFZ commented on src/utils/apiSignup.js
> +  if (result.status === 400 ) {
Igual que antes, comprueba antes si `result` no es undefined

2019-09-23 21:47 UTC, SabrinaFZ commented on src/utils/apiSignup.js
> +  if (result.status === 201 ) {
Lo mismo que arriba, comprueba antes si result no es undefined

2019-09-23 21:48 UTC, SabrinaFZ requested changes
Perdona por tantos comentarios!

2019-09-24 16:12 UTC, hvctgr commented on src/components/Signup/Signup.js
> +      if (result.error === false) {
Mejor como dices, mas claro tambien!

2019-09-24 16:12 UTC, hvctgr commented on src/utils/apiSignup.js
> +const BASE_URL = 'http://127.0.0.1:8000/api/v1/';
hecho!

2019-09-25 05:42 UTC, SabrinaFZ approved these changes

2019-09-26 21:30 UTC, bri06 commented on public/index.html
> +    <link href="//netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" />
🙈

2019-09-26 21:30 UTC, bri06 approved these changes

2019-09-26 21:30 UTC, bri06 commented
Faltaría resolver los conflitos

2019-09-28 10:36 UTC, merged